### PR TITLE
Display jumping fix useless decompilation

### LINKED ISSUE #2270: Decompiler view jumps when toggling a breakpoint or adding a comment
**Environment information**
* Operating System: Ubuntu 20.04
* Cutter version: Latest master
  - [x] Built from source
  - [ ] Downloaded from release
  - [ ] Distribution repository

**Describe the bug**
Toggling a breakpoint(or adding a comment) in the decompiler widget causes the view to jump. This makes it difficult to keep track on the position of code you are looking at. 

**To Reproduce**
1. Open a ~2 screens high function and scroll down a bit
2. Select a line somewhere in the middle and add a breakpoint(or comment).
3. Observe that viewing position in the decompiler widget changes

See this GIF to see exactly what's happening
display jumps

**Expected behavior**

The view should not move while adding toggling a breakpoint. But the highlighting of the line should change accordingly.

**Findings so far (for the problem with toggling breakpoints)**
After hours of debugging, I found that this view jumping problem happens because the whole code gets decompiled again when a new breakpoint is added. Then the code tries to reset the cursor to the previous location(the line at which the breakpoint was toggled). That's how we at least get to see the line at which the breakpoint was added. But the view doesn't get back to the way it was.

### PR DESCRIPTION
**Pull request by NirmalManoj**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [ ] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

The important modifications and additions in this PR are:
1. Saves the previous function's address and if the newly decompiled function is the same as the previous one, the scroll position will remain the same.
2. Modified signal `breakpointsChanged()` to `breakpointsChanged(RVA offset)`. Removed `emit instructionChanged` from all functions that emit `breakpointsChanged`.

Display jumps while toggling breakpoint (Before)
BeforeFixingDisplayJumping
Display position doesn't change while toggling breakpoint (After)
AfterFixingDisplayJumping

You can notice the same change in other actions also, e.g. Add/Rename/Remove names, Refresh, Add/Delete/Modify comments, etc.

**Test plan (required)**
1. Test to make sure that the breakpoints are toggled and highlighted properly in the decompiler and ensure if the display position is getting changed.
2. See if the display position is changing when the view is refreshed using the refresh button.
3. Notice the changes in the display that happens when an instruction is modified. For example, change an if condition from `je address` to `jne address` and see if the display changes in an undesirable way.
4. Open the following three widgets in sync (Decompiler, Disassembly, Graph). Toggle breakpoints and make sure that every single change is reflected properly in all the widgets.

**Closing issues**
closes #2270

### CODE REVIEW

File: src/widgets/DecompilerWidget.cpp [hunk 1]
```diff
@@ -182,6 +186,20 @@ static size_t positionForOffset(RAnnotatedCode &codeDecompiled, ut64 offset)
...
 }
 
+void DecompilerWidget::updateBreakpoints()
+{
+    setInfoForBreakpoints();
+    QTextCursor cursor = ui->textEdit->textCursor();
+    cursor.select(QTextCursor::Document);
+    cursor.setCharFormat(QTextCharFormat());
+    cursor.setBlockFormat(QTextBlockFormat());
+    cursor.clearSelection();
```
Comment (karliss) [inline src/widgets/DecompilerWidget.cpp:196]: Does this code have any effect?

Comment (NirmalManoj) [reply src/widgets/DecompilerWidget.cpp:196]: @karliss It clears the existing highlights.

File: src/widgets/DisassemblyWidget.cpp [hunk 2]
```diff
@@ -249,6 +246,13 @@ QList<DisassemblyLine> DisassemblyWidget::getLines()
     return lines;
 }
 
+void DisassemblyWidget::refreshIfInRange(RVA offset)
+{
+    if (offset >= topOffset && offset <= bottomOffset) {
+        refreshDisasm();
+    }
+}
+
```
Comment (NirmalManoj) [inline src/widgets/DisassemblyWidget.cpp:255]: > I sometimes noticed a situation where I select a line in decompiler, add a breakpoint and breakpoint appears in disassembly but not the decompiler. It's hard to tell if it's an actual problem or just r2ghidra returning bad offset<->line mapping.

@karliss  Not perfect offset<->line mapping exist, and because of that when you click on a line to add a breakpoint, another line could get highlighted. This can be improved. Just to confirm, did you observe this or did no breakpoint appear at all?

File: src/widgets/DecompilerWidget.cpp (hunk 1 above)
Comment (karliss) [reply src/widgets/DecompilerWidget.cpp:196]: Ok, got slightly confused by Qt API due to cursor both representing a range from document and also being used to manipulate the document. Something like `textEdit->setCharFormat(cursor, format)` would have been more obvious, but the API is what it is.

I don't think the last line `cursor.clearSelection()` is necessary since it isn't used for anything afterwards.

File: src/widgets/DisassemblyWidget.cpp (hunk 2 above)
Comment (karliss) [reply src/widgets/DisassemblyWidget.cpp:255]: In some cases where single instructions maps to multiple lines of code the breakpoint got added to different line. That's understandable since there is no 1:1 mapping. I don't think it needs too much improvement.

But that's not what I meant.  I was referring to situations  where no breakpoint appeared in decompiler.

File: src/core/Cutter.cpp [hunk 3]
```diff
@@ -2068,23 +2068,20 @@ void CutterCore::setDebugPlugin(QString plugin)
...
-    emit breakpointsChanged();
+    emit breakpointsChanged(addr);
 }
 
 void CutterCore::toggleBreakpoint(QString addr)
 {
     cmdRaw("dbs " + addr);
-    emit instructionChanged(addr.toULongLong());
-    emit breakpointsChanged();
+    emit breakpointsChanged(addr.toULongLong());
```
[the remark this answers is not in the document]
Comment (NirmalManoj) [reply src/core/Cutter.cpp:2077]: @karliss Earlier, the code was doing `emit instructionChanged(addr.toULongLong())`. That's why I directly did the same with the new signal. 

As I understand now, both of these functions are not used anymore. So if you want me to remove them, I can do that. But I think it doesn't hurt to have these two functions here.

File: src/widgets/DisassemblyWidget.cpp (hunk 2 above)
Comment (NirmalManoj) [reply src/widgets/DisassemblyWidget.cpp:255]: @karliss I think it probably appeared outside the screen because if it's not a bug, it's supposed to appear at exactly one line on the screen. Could you check it once again to make sure?

File: src/core/Cutter.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (karliss) [reply src/core/Cutter.cpp:2077]: Unless you fix them It will hurt once someone tries to use them and breakpoints disappear or appear in wrong address.

[the remark this answers is not in the document]
Comment (NirmalManoj) [reply src/core/Cutter.cpp:2077]: @karliss How will it hurt if it's used correctly? That is, passing an integer address as a string.

File: src/widgets/DecompilerWidget.cpp (hunk 1 above)
Comment (NirmalManoj) [reply src/widgets/DecompilerWidget.cpp]: I have removed the last line now.

File: src/core/Cutter.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (NirmalManoj) [reply src/core/Cutter.cpp]: @karliss I have removed `addBreakpoint(QString)`. Changed `toggleBreakpoint(QString)` to this
```
void CutterCore::toggleBreakpoint(QString addr)
{
    toggleBreakpoint(addr.toULongLong());
}
```

[the remark this answers is not in the document]
Comment (karliss) [reply src/core/Cutter.cpp]: Please don't do that. I already explained you once above that if a function accepts a string which is only allowed to be a number it should better accept it directly thus checking that correct thing is passed at compile time using type system and also avoid unnecessary conversion to string and back. All other CutterCore functions which accept string as address support expression.

[the remark this answers is not in the document]
Comment (NirmalManoj) [reply src/core/Cutter.cpp]: I understand the problem with this. I have removed `toggleBreakpoint(QString addr)` now.

**Comment by ITAYC0HEN** [comment]
Does this PR is using functionalities from the decompiler-refactoring? if not, maybe this can be pushed to maste as it is a bug-fix\improvement which is small and can be enjoyed by our users. What do you think?

**Comment by NirmalManoj** [comment]
@ITAYC0HEN Yes, we have improved "DecompilerWidget" and this uses some improvements and features in decompiler-refactoring (e.g. `setInfoForBreakpoints()`).  It shouldn't take more than 10-12 days to get `decompiler-refactoring` ready to get merged to master.

**Comment by ITAYC0HEN** [comment]
Thanks! <3

File: src/widgets/DisassemblyWidget.cpp (hunk 2 above)
Comment (NirmalManoj) [reply src/widgets/DisassemblyWidget.cpp:255]: @karliss Did you check this? I think I can safely assume that breakpoint did appear in a line outside the screen. Apart from this, are you waiting for any other changes in this PR?

Comment (karliss) [reply src/widgets/DisassemblyWidget.cpp:255]: I wasn't able to repeat this reliably, I will let you know if notice this again.
