### PR TITLE
Focus on visible disasm or graph

### LINKED ISSUE #1284: Emulation button is selected by default
**Describe the bug**

Emulation button is selected by default so when I open Cutter and want to switch to graph view by pressing <kbd>space</kbd> it actually starts the Emulation.

**To Reproduce**

1. Start Cutter
2. Press space

**Expected behavior**

Switch to graph mode.

### PR DESCRIPTION
**Pull request by optizone**
Now as @xarkes mentioned "start emulation" button has focus on start of Cutter. 
I changed it so first visible disasm or graph widget has focus or if there are no visible disasm or graph - "start emulation" button has.

**Closing issues**
closes #1284

### CODE REVIEW

File: src/core/MainWindow.cpp [hunk 1]
```diff
@@ -588,6 +588,18 @@ void MainWindow::finalizeOpen()
     // Add fortune message
     core->message("\n" + core->cmd("fo"));
     showMaximized();
+
+    // Set focus to disasm or graph widget
+    const QString disasmWidgetClassName = disassemblyDock->metaObject()->className();
+    const QString graphWidgetClassName = graphDock->metaObject()->className();
+    for (auto dockWidget : dockWidgets) {
```
Comment (xarkes) [inline src/core/MainWindow.cpp]: I think the for loop is not necessary as you should already have a pointer to the graph and disassembly view as an attribute of MainWindow, am I wrong?

Comment (optizone) [reply src/core/MainWindow.cpp]: It is for cases when there are two or more disasm/graph widgets. So if second widget is visible Cutter focuses on it and not on first(non-visible) one

File: src/core/MainWindow.cpp [hunk 2]
```diff
@@ -588,6 +588,19 @@ void MainWindow::finalizeOpen()
     // Add fortune message
     core->message("\n" + core->cmd("fo"));
     showMaximized();
+
+    // Set focus to disasm or graph widget
+    setFocus();
+    const QString disasmWidgetClassName = disassemblyDock->metaObject()->className();
+    const QString graphWidgetClassName = graphDock->metaObject()->className();
+    for (auto dockWidget : dockWidgets) {
```
Comment (ITAYC0HEN) [inline src/core/MainWindow.cpp]: This for loop won't stop even when found Graph or Disas widgets

File: src/core/MainWindow.cpp [hunk 3]
```diff
@@ -588,6 +588,19 @@ void MainWindow::finalizeOpen()
...
+        const QString className = dockWidget->metaObject()->className();
+        if ((className == disasmWidgetClassName ||
```
Comment (ITAYC0HEN) [inline src/core/MainWindow.cpp]: I believe that Graph widget should get priority over Disassembly widget (in case that there is a function to show there)

File: src/core/MainWindow.cpp (hunk 1 above)
Comment (xarkes) [reply src/core/MainWindow.cpp]: Ok then it's probably worth adding a comment to tell why you used a for loop ;)

File: src/core/MainWindow.cpp [hunk 4]
```diff
@@ -588,6 +588,43 @@ void MainWindow::finalizeOpen()
...
+
+
+    // Set focus to disasm or graph widget
+
+    // Use for loop to cover cases when main disasm/graph
+    // (MainWindow::disassemblyDock and MainWindow::graphDock)
+    // widgets are invisible but extra ones are visible
+
+    // Graph with function in it has focus priority over DisasmWidget
+    // if there are bot graph and disasm.
```
Comment (ITAYC0HEN) [inline src/core/MainWindow.cpp]: both*

**Comment by ITAYC0HEN** [comment]
Looks good and works. Didn't check all the edge cases but looks good. Fix the typo and I will merge
