### PR TITLE
Fix #872: Update seek after console tasks finishes

### LINKED ISSUE #872: s 0xADDR dont work
**Environment information**
* Operating System:
kali rolling amd64
* Cutter version:
Cutter 1.7.2 (Fri Oct 19 15:11:37 2018 +0300)
radare2 3.0.0 19993 @ linux-x86-64 git.2.9.0-407-g734b3d73b
commit: 734b3d73ba3987e3213ca53e9715c3da63196b9b build: 2018-10-19__23:16:33
* File format:
elf64 (/bin/ls)

**Describe the bug**
Dont work jump via "s ADDRESS" command in command bar. This feature worked a couple of month ago.

**To Reproduce**
Just type "s 0xaddress"

**Expected behavior**
I expected immediate jump in Graph or Disassembly views

### PR DESCRIPTION
**Pull request by fcasal**
Fixes https://github.com/radareorg/cutter/issues/872

### CODE REVIEW

**Comment by xarkes** [comment]
Not very elegant, but it will fix it for now indeed.
I think it will "freeze" the user interface each time a command is typed?

File: src/widgets/ConsoleWidget.cpp [hunk 1]
```diff
@@ -188,6 +188,7 @@ void ConsoleWidget::executeCommand(const QString &command)
         commandTask = nullptr;
         ui->inputLineEdit->setEnabled(true);
         ui->inputLineEdit->setFocus();
+        Core()->updateSeek();
```
Comment (xarkes) [inline src/widgets/ConsoleWidget.cpp]: I'd rather make sure the seek was effectively changed before trying to update anything.
I think you can store current seek into a variable, and call updateSeek only if different.
