### PR TITLE
Detach Cutter interface from debug command execution

### LINKED ISSUE #1848: Running a program in debug mode will freeze Cutter
**Environment information**
* Operating System: Arch Linux
* Cutter version: Recent Debug branch
* File format: Any

**Describe the bug**

While in debug mode, and clicking the Continue\Run button. The debugee is being executed and runnning. But the interface of Cutter itself froze and is not responsive.

**To Reproduce**

1. Open the Cutter binary in Cutter. Analyze quickly. you can stop the analysis in the middle
2. Start Debugging
3. Press the Continue button
4. See that the new Cutter (the debuggee) is running, but the interface of the original Cutter (the debugger) is not responsive.
5. Close the debuggee and see that the debugger is now back to be responsive

**Expected behavior**

The interface should keep being responsive

**Screenshots**

### PR DESCRIPTION
**Pull request by yossizap**
**Detailed description**

As #1848 describes, the Cutter interface freezes when executing commands. This happens because those r2 commands are called with cmd() directly instead of the AsyncCommand class. R2 expects the user to send a signal using the keyboard for it to exit *_dbg_wait similarly to gdb so it isn't an issue there. 

This PR offers a solution that uses the AsyncCommand class, atm there's only support for regular debugging to get your feedback but I plan on adding this feature to emulation as well, can also be handy with other slow commands.
The commands calling AsyncCmd are responsible of disabling the debug toolbar(and possibly other things as well in the future) and connecting to the finished() event(decided not to go with passing callbacks to AsyncCmd since it's too messy and QSharedPointer take care of setting the asynctask pointer to NULL once all clients are done with their logic).

There also needs to be a some kind of "Suspend" button that will stop the async task using a new r2 command/signal.

**Test plan (required)**

Run "continue until main" twice or just "continue" without breakpoints to see that all toolbar buttons are disabled except for stop/restart. Running any of the step commands will momentarily disable the buttons so it's harder to see that it's working.

**Closing issues**

closes #1848

### CODE REVIEW

**Comment by yossizap** [comment]
See "Added AsyncCmd for debug commands", the other commits are waiting for a merge in a different PR/branch. I'll rebase once it's done.

File: src/core/Cutter.h [hunk 1]
```diff
@@ -435,6 +453,9 @@ class CutterCore: public QObject
 
     void projectSaved(bool successfully, const QString &name);
 
+    void disableDebugToolbar();
+    void enableDebugToolbar();
```
Comment (thestr4ng3r) [inline src/core/Cutter.h]: Emitting enable/disable directly in many places is error-prone, especially if the enabled state will later depend on more things. Instead, there should be only one signal which can be called something like `debugStateChanged()` and the toolbar itself will check if the process is currently running, etc. and update accordingly.

File: src/core/Cutter.h [hunk 2]
```diff
@@ -479,6 +500,8 @@ class CutterCore: public QObject
 
     bool emptyGraph = false;
     BasicBlockHighlighter *bbHighlighter;
+
+    QSharedPointer<CommandTask> commandTask;
```
Comment (thestr4ng3r) [inline src/core/Cutter.h]: `commandTask` is too generic. There can be many tasks running at the same time for all kinds of things. This should be called something like `debugRunTask` instead and the `asyncCmd()` method also needs a more debug-specific name.

File: src/core/Cutter.cpp [hunk 3]
```diff
@@ -318,6 +312,31 @@ QString CutterCore::cmd(const char *str)
...
+{
+    if (!commandTask.isNull()) {
+        return nullptr;
+    }
+
+    CORE_LOCK();
+
+    RVA offset = core->offset;
+
+    commandTask = QSharedPointer<CommandTask>(new CommandTask(str, CommandTask::ColorMode::MODE_256, true));
```
Comment (thestr4ng3r) [inline src/core/Cutter.cpp]: I think you can use `R2Task` instead of `CommandTask` since it's more lightweight and also supports breaking.

File: src/core/Cutter.h (hunk 2 above)
Comment (yossizap) [reply src/core/Cutter.h]: commandTask - Placeholder name, will do.
asyncCmd - I was thinking this function could be used for various async tasks by other parts of the code/plugins as well, it doesn't have anything specific to debug commands except for the commandTask check.
What do you think about passing an R2/AsyncTask class to asyncCmd and have the debug/plugin/other entity handle the limit on it's concurrency?

File: src/core/Cutter.cpp (hunk 3 above)
Comment (yossizap) [reply src/core/Cutter.cpp]: Agreed but the tasksIndicator progress wheel is good UX in addition to the greyed out buttons that may be a bit confusing. 

I was thinking of three options:
* Write a more generic task handler for AsyncTasks and R2Tasks
* Hijack the signal(with some code in mainwindow's tasksChanged callback)
* Create another progress wheel near the debug icons?

**Comment by yossizap** [comment]
> I am not sure yet whether breaking dc in a task work in r2 yet, but this is the way it is supposed to work.
Seems to work fine.

File: src/core/Cutter.h (hunk 1 above)
Comment (yossizap) [reply src/core/Cutter.h]: Mm I would like to specifically disable the toolbar while stopping/restarting debugging. Not sure if it's critical though.

Comment (thestr4ng3r) [reply src/core/Cutter.h]: What I proposed wouldn't change the behavior, only the architecture. Or is there something unclear about it? Basically you would merge those two signals into one and make the toolbar itself determine whether to enable or disable.

File: src/core/Cutter.cpp (hunk 3 above)
Comment (thestr4ng3r) [reply src/core/Cutter.cpp]: That indicator is more meant for actual busy processes in the background. For debug, I would rather add some other kind of indicator. So basically the 3rd option, but not necessarily as a progress wheel.

File: src/core/Cutter.h (hunk 1 above)
Comment (yossizap) [reply src/core/Cutter.h]: I meant that the toolbar won't be able to determine that there's a process in progress when there's no actual task happening, which is the case of stopDebug for example. Thinking of it now, I could check "currentlyDebugging" to bypass this issue.

Comment (thestr4ng3r) [reply src/core/Cutter.h]: Yes, it should be possible to always determine the not-debugging/running/stopped state in some way.

**Comment by yossizap** [comment]
I was mislead by r2's output when checking &b on debug commands, you can't actually resume. I am looking into the issue on r2's side. 

Everything else is pretty much as I think it should be in it in it's final form apart from other UX elements that indicate debug task progress. Will keep this PR as a draft until it's solved, just note that the suspend button won't actually do anything until &b for debug commands is fixed.

**Comment by yossizap** [comment]
The latest version should work well on Linux and some r2 bugs were fixed alongside `&` issues, tested with remote and local.

Windows is also broken and it might take a while since I am less familiar with it. Would appreciate it if you would test this branc on Mac and provide some feedback on the existing solution now that things seem to be fully working.

**Comment by ITAYC0HEN** [comment]
Will check this PR later today on windows. Will merge if the status is OK. unless someone think otherwise

**Comment by xarkes** [comment]
I see the build is errored, restart it to make sure it's fine on OS X.
