### PR TITLE
Add feature to apply structure offset and fix some issues in EditVariablesDialog

### LINKED ISSUE #1072: Add right click apply structure in the graph

### LINKED ISSUE #1073: Add right click apply structure in the disassembly

### PR DESCRIPTION
**Pull request by m0nk3ydluffy**
This pull request:

1. Adds the feature to apply structure offset from the context menus of disassembly and graph view.
2. Fixes EditVariablesDialog such that the view is refreshed after changes and structs are shown only once in the combo box.

As discussed in #1073 , I have only added the basic functionality. Following are the things on which we can work on in r2 for further improvements:

1. `tas <offset>` currently does not support returning output in json (`tasj`) so I have marked it as a TODO in comments. 
2. I couldn't find a way to undo the applying of structure offset, so maybe that will need to be implemented too. (Sorry if it already exists.)

Closes #1072  , closes #1073 

structureoffset

### CODE REVIEW

File: src/core/Cutter.cpp [hunk 1]
```diff
@@ -565,6 +565,16 @@ void CutterCore::setCurrentBits(int bits, RVA offset)
     emit instructionChanged(offset);
 }
 
+void CutterCore::applyStructureOffset(const QString &structureOffset, RVA offset)
+{
+    if (offset == RVA_INVALID) {
+        offset = getOffset();
+    }
+
+    this->cmd("ta " + structureOffset + " @ " + QString::number(offset));
```
Comment (ITAYC0HEN) [inline src/core/Cutter.cpp]: Can a potential attacker control "structure offset" in order to inject and execute r2 command?

Comment (thestr4ng3r) [reply src/core/Cutter.cpp]: Just use cmdRaw, that should work.

Comment (m0nk3ydluffy) [reply src/core/Cutter.cpp]: Okay! Thanks. I'll use cmdRaw().
