### PR TITLE
Interface theme and theme features refactoring

### LINKED ISSUE #1595: Color change regression caused by #1533
**Environment information**
* Operating System: ArchLinux
* Cutter version: 31838a3a35f42fab0254f0a03aa1181ca420fb36
* File format: any

**Describe the bug**

When changing color theme hexwidget colors don't change.

**To Reproduce**

1. Open hexwidget
2. switch color theme
3. observe that colors didn't change

**Expected behavior**

HexWidget reacts to color theme changes

**Additional context**

Seems to be caused by #1533 as I couldn't repeat the problem using 214e6f426458a793ef836cb682156e1584e29c02 . Inserting debug messages indicated that `colorsUpdated` signal and connected methods get triggered color before and after doesn't change.

### PR DESCRIPTION
**Pull request by optizone**
**Detailed description**
Changes way of handling theme and interface theme changing. Also computes ColorFlag for native theme so only relevant themes are shown. Improves performance (switching between standard themes goes from 0.6 sec to 0 sec). `ColorThemeWorker::getTheme` now works how it is expected. 
Also background for transparent colors was added to options list view so they don't merge with widget's background.
image

**Closing issues**
closes #1595

### CODE REVIEW

File: src/common/ColorThemeWorker.cpp [hunk 1]
```diff
@@ -160,15 +161,29 @@ bool ColorThemeWorker::isThemeExist(const QString &name) const
...
+        theme = Core()->cmdj("ecj").object().toVariantMap();
         Core()->cmd(QString("eco %1").arg(curr));
     } else {
-        theme = Core()->cmdj("ecj").object();
+        theme = Core()->cmdj("ecj").object().toVariantMap();
+    }
+
+    for (auto it = theme.begin(); it != theme.end(); it++) {
+        auto arr = it.value().toList();
+        if (arr.size() == 4) {
```
Comment (xarkes) [inline src/common/ColorThemeWorker.cpp]: Why 4? What does it correspond to? If it's very obvious you can use a constant or `#define`, otherwise add a comment :)

File: src/widgets/ColorThemeListView.cpp [hunk 2]
```diff
@@ -133,7 +133,24 @@ void ColorOptionDelegate::paint(QPainter *painter,
 
     QPainterPath roundedColorRect;
     roundedColorRect.addRoundedRect(colorRect, fontHeight / 4, fontHeight / 4);
-    painter->setPen(Qt::NoPen);
+    if (currCO.color.alpha() < 255) {
+        QPixmap p(colorRect.size());
+        QPainter paint(&p);
+        const int c1 = colorRect.width() / 4;
+        const int c2 = c1 / 2;
+        for (int y = 0; y < colorRect.height(); y++) {
```
Comment (xarkes) [inline src/widgets/ColorThemeListView.cpp]: Maybe add a comment to explain what this double for loop does (and why a drawRectangle is not enough), it will be faster to understand :)

Comment (karliss) [reply src/widgets/ColorThemeListView.cpp]: Since the pattern gets applied as brush, I would expect that repeating it once by iterating until colorRect.width()/4 to be sufficient. That results in brush pattern containing 2 rectangles which could be painted using drawRect instead of manually iterating over all pixels.

File: src/common/ColorThemeWorker.cpp (hunk 1 above)
Comment (optizone) [reply src/common/ColorThemeWorker.cpp]: Actually, this comparison makes no sense. It was late at night so I think I wrote it by mistake :)

Comment (ITAYC0HEN) [reply src/common/ColorThemeWorker.cpp]: LOOOL XD

File: src/widgets/ColorThemeListView.cpp [hunk 3]
```diff
@@ -133,7 +133,19 @@ void ColorOptionDelegate::paint(QPainter *painter,
 
     QPainterPath roundedColorRect;
     roundedColorRect.addRoundedRect(colorRect, fontHeight / 4, fontHeight / 4);
-    painter->setPen(Qt::NoPen);
+    if (currCO.color.alpha() < 255) {
```
Comment (xarkes) [inline src/widgets/ColorThemeListView.cpp]: I'd still add a comment like `// Draw the alpha color box` but maybe that's because I'm too bad.

Comment (ITAYC0HEN) [reply src/widgets/ColorThemeListView.cpp]: Yes please, more informative comments are good :)
Other than that, we both approved so we thi is its good to go
