### PR TITLE
ThreadsWidget and r2 debugging fixes

### LINKED ISSUE #1019: List threads
List threads in debug mode with `dpt` in radare2

### LINKED ISSUE #1020: Ability to change thread
Ability to change thread in debug mode using `dpt=` requires #1019.

### PR DESCRIPTION
**Pull request by yossizap**
**Detailed description**

Added a widget that shows thread information and allows thread switching. The r2 update also includes a fix to drrj that caused RegistersWidget to print incorrect register values.

For some reason the widget shows up when not in debug mode in window, would appreciate it if you could take a look at it. I followed backtracewidget's and stackwidget's behavior so I am not sure why it would happen.

**Test plan (required)**

Debug multi-threaded processes, see that all threads show up and attempt to switch threads using the UI.

Testing points:
- UI shows the correct position in the disassembly window when switching threads
- Newly created threads are added to the UI
- Thread's data is immediately synced(regs, stack, backtrace, position) when switching without having to step
- ThreadsWidget's UI is cleared after restarting the debugging session

Example binary(play around with the number of threads and thread_func's content as desired):
```
#include <thread>

void thread_func() {
    int64_t counter = 0;
    while(true) {
        ++counter;
    }
}

 int main() {
    std::thread t1(thread_func);
    std::thread t2(thread_func);
    ...
    t1.join();
    t2.join();
    ...
}
```
**Closing issues**

closes #1020 
closes #1019

### CODE REVIEW

**Comment by ITAYC0HEN** [comment]
Thanks for the PR! :)
I will look at it tomorrow. meantime - can you please re-write the test-case with a specific example? It would be great if you will even attach a binary and write some short steps so we can test it better. 

Thanks!

File: src/core/Cutter.cpp [hunk 1]
```diff
@@ -1117,6 +1127,13 @@ void CutterCore::setRegister(QString regName, QString regValue)
     emit refreshCodeViews();
 }
 
+void CutterCore::setCurrentDebugThread(int tid)
+{
+    cmdj("dpt=" + QString::number(tid));
```
Comment (ITAYC0HEN) [inline src/core/Cutter.cpp]: cmdj --> cmd
No need to jsonize it

File: src/widgets/ThreadsWidget.cpp [hunk 2]
```diff
@@ -0,0 +1,120 @@
...
+}
+
+void ThreadsWidget::onDoubleClicked(const QModelIndex &index)
+{
+    if (!index.isValid())
+        return;
+
+    int row = index.row();
+
+    QJsonArray threadsValues = Core()->getProcessThreads(DEBUGGED_PID).array();
```
Comment (karliss) [inline src/widgets/ThreadsWidget.cpp]: Instead of hoping that thread order and count doesn't change you can store the thread id in list item using @QStandardItem::setData@ or something similar.

**Comment by yossizap** [comment]
>can you please re-write the test-case with a specific example? It would be great if you will even attach a binary and write some short steps so we can test it better.

I'll update it with a more throughout plan but as for the binary all you need is a variation of

    #include <thread>

    void thread_func() {
        int64_t counter = 0;
        while(true) {
            ++counter;
        }
    }

     int main() {
        std::thread t1(thread_func);
        std::thread t2(thread_func);
        ...
        t1.join();
        t2.join();
        ...
    }

File: src/widgets/ThreadsWidget.cpp (hunk 2 above)
Comment (yossizap) [reply src/widgets/ThreadsWidget.cpp]: Why would it change? The table isn't sortable and this signal is activated the moment the user activates the row that he wants to switch to. 
Each time dptj returns a different result the threadsValues change accordingly.

File: src/core/Cutter.cpp [hunk 3]
```diff
@@ -1211,6 +1230,7 @@ void CutterCore::stopDebug()
 void CutterCore::syncAndSeekProgramCounter()
 {
     QString programCounterValue = cmd("dr?`drn PC`").trimmed();
+    printf("programcountervalue %s\n", programCounterValue.toStdString().c_str());
```
Comment (ITAYC0HEN) [inline src/core/Cutter.cpp]: debug leftovers?

File: src/widgets/ThreadsWidget.cpp [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+    ui->viewThreads->setModel(modelThreads);
+    ui->viewThreads->resizeColumnsToContents();;
+}
+
+void ThreadsWidget::fontsUpdatedSlot()
+{
+    ui->viewThreads->setFont(Config()->getFont());
+}
+
+void ThreadsWidget::onActivated(const QModelIndex &index)
```
Comment (ITAYC0HEN) [inline src/widgets/ThreadsWidget.cpp]: what do you think? I wonder whether should it trigger a seek to thread's instruction pointer

File: src/core/Cutter.cpp (hunk 3 above)
Comment (yossizap) [reply src/core/Cutter.cpp]: Whoops, sorry about that

File: src/widgets/ThreadsWidget.cpp (hunk 4 above)
Comment (yossizap) [reply src/widgets/ThreadsWidget.cpp]: OnActivated calls setCurrentDebugThread that already takes care of all the updates I could find - https://github.com/yossizap/cutter/blob/debug/src/core/Cutter.cpp#L1133-L1136. Seemed more correct to have the UI update events in Cutter.cpp, similarly to other debug functions.

File: src/widgets/ThreadsWidget.cpp (hunk 2 above)
Comment (karliss) [reply src/widgets/ThreadsWidget.cpp]: Why would it not change? R2 has no documentation stating that result will be in specific order or conditions under which it will not change. The thread list could be coming from a plugin with external debugger doing who knows what. Table can't be sorted right now, but that or filtering would be reasonable functionality for dealing with program that has large amount of threads. Cutter currently freezes while the program is running, but once its fixed there would be a possibility of new threads being created or destroyed. My point is that it is bad assumption that can be easily avoided.

Comment (yossizap) [reply src/widgets/ThreadsWidget.cpp]: Well it would not change because every time CutterCore sends refreshAll or seekChanged(Also called when switching threads), modelThreads is [re-created in whichever order the plugin sends the thread list](https://github.com/yossizap/cutter/blob/debug/src/widgets/ThreadsWidget.cpp#L73-L90) and the [old rows are deleted](https://github.com/yossizap/cutter/blob/debug/src/widgets/ThreadsWidget.cpp#L92-L95). Meaning that the UI's rows are always synced with whatever output r2 returns.

If there's an interest in adding sorting/filters I wouldn't mind going your way but I just wanted to make that clear.

**Comment by karliss** [comment]
Not exactly a problem of this issue, but I wasn't able to get the test program to the point of multiple threads.
* start debugging
* "Refresh contents" to update addresses in function widget
* set breakpoint in thread_func
* continue -> no threads, the process got killed?

**Comment by yossizap** [comment]
Which system? Make sure you have updated the r2 subrepo updates and rebuilt everything..

Compiled with `g++ -O3 -std=c++11 -o main test.c -lpthread`, no issues

Untitled

**Comment by karliss** [comment]
Putting a breakpoint between creating threads and join, somewhat helped. After manually requesting refresh threads appeared. At that point I was able to switch between threads.

File: src/widgets/ThreadsWidget.cpp (hunk 4 above)
Comment (karliss) [reply src/widgets/ThreadsWidget.cpp]: Confirmed that seeking to threads instruction pointer already works.

File: src/widgets/ThreadsWidget.cpp (hunk 2 above)
Comment (ITAYC0HEN) [reply src/widgets/ThreadsWidget.cpp]: yeah sorting+filters are recommended as default in all these types of widget

**Comment by ITAYC0HEN** [comment]
> After manually requesting refresh threads appeared

In my case the threads were shown immediately.

**Comment by ITAYC0HEN** [comment]
Tested again. Looks very good to me. I'd behapy to see the column sorting additions and the filters. Other than that, it is good to go :)

**Comment by karliss** [comment]
Looks good only remaining problem is opening outside debug mode. I suggest giving it a few more days and if no one (including me) comes up with a fix or time to investigate it merge it in current state.

**Comment by ITAYC0HEN** [comment]
what do you mean by "opening outside debug mode"?
also, this is a pull request to merge to Debug branch so anyway this is not a user-facing branch. Thus I believe that this state is a good progress anyway so as long as all the issues are documented and on the Debug roadmap, don't see a reason to wait more

**Comment by karliss** [comment]
Right, forgot about debug branch. No more complains except failed Ubuntu 16.04 job. Should be easy to fix.

**Comment by yossizap** [comment]
Didn't notice I have used newer Qt methods that weren't available in Qt5.3, hopefully this will fix it.

Regarding the "opening outside debug mode", I'll keep looking into it but I am not really sure why it's not working as intended since everything is properly configured in MainWindow. Would appreciate it if you would look into it as well.
