### PR TITLE
Remove newline at end of strings in StackWidget.

### LINKED ISSUE #1784: Copying values from Stack widget have an extra new line
**Describe the bug**

Sometimes, when copying a value from the Stack widgets there is a trailing new line copied to the clipboard

**To Reproduce**

1. Open Megabeets_0x1
2. Start emulation from 0x080485a3 
3. Step over few times until reaching sym.rot13
4. Copy the string shown at the top of the stack widget ("Megabeets" or "Zrtnorrgf")
5. Paste it on notepad and notice the new line

**Expected behavior**

The value should not be with a new line unless it is there in the string.

**Screenshots**

### PR DESCRIPTION
**Pull request by nullsector**
Removed whitespace via trimmed() from the QString for StackWidget in order for the copy/paste to operate as intended. 

closes #1784

### CODE REVIEW

File: src/widgets/StackWidget.cpp [hunk 1]
```diff
@@ -79,7 +79,9 @@ void StackWidget::setStackGrid()
     for (const QJsonValue &value : stackValues) {
         QJsonObject stackItem = value.toObject();
         QString addr = RAddressString(stackItem["addr"].toVariant().toULongLong());
+	addr = addr.trimmed();
```
Comment (karliss) [inline src/widgets/StackWidget.cpp]: If a string obtained by converting integer to string contains newline something is terribly broken and that function should be fixed. I assume that this isn't the case and trimming here is unnecessary.

File: src/widgets/StackWidget.cpp [hunk 2]
```diff
@@ -88,6 +90,7 @@ void StackWidget::setStackGrid()
         QJsonValue refObject = stackItem["ref"];
         if (!refObject.isUndefined()) { // check that the key exists
             QString ref = refObject.toString();
+	    ref = ref.trimmed();
```
Comment (karliss) [inline src/widgets/StackWidget.cpp]: Please check the formatting. I think you are mixing tabs with spaces. The coding style is described here.

File: src/widgets/StackWidget.cpp [hunk 3]
```diff
@@ -88,6 +90,7 @@ void StackWidget::setStackGrid()
...
             if (ref.contains("ascii") && ref.count("-->") == 1) {
                 ref = Core()->cmd("psz @ [" + addr + "]");
```
Comment (ITAYC0HEN) [inline src/widgets/StackWidget.cpp]: `ref` might be changed here again so the trim should take place later and not few rows above. 
Also, and even more important, it is most likely that this is the row that causes the newline to appear since iirc the command `psz`  have a trailing new line at the end, as any other `cmd` commands (in contrary to `cmdj`). You might want to look at this.

Most likely, you can fix this issue simply by changing `cmd("psz @ [addr]")` to `cmdj("pszj @ [addr]")` and grab the "string" item. Instead of trimming

File: src/widgets/StackWidget.cpp (hunk 1 above)
Comment (nullsector) [reply src/widgets/StackWidget.cpp]: Agreed. Will look further into how the newline is getting introduced while copying data from the QTableView for a cell.

Comment (nullsector) [reply src/widgets/StackWidget.cpp]: Used solution proposed by @ITAYC0HEN

File: src/widgets/StackWidget.cpp (hunk 3 above)
Comment (nullsector) [reply src/widgets/StackWidget.cpp]: Made the change you recommended. Have trouble testing as I am struck with the qmake issue on Debian that was referenced here: #1797

File: src/widgets/StackWidget.cpp [hunk 4]
```diff
@@ -89,7 +89,7 @@ void StackWidget::setStackGrid()
         if (!refObject.isUndefined()) { // check that the key exists
             QString ref = refObject.toString();
             if (ref.contains("ascii") && ref.count("-->") == 1) {
-                ref = Core()->cmd("psz @ [" + addr + "]");
+                ref = Core()->cmdj("pszj @ [" + addr + "]");
```
Comment (ITAYC0HEN) [inline src/widgets/StackWidget.cpp]: sadly, this would not work.
First, you are not parsing the JSON anywhere. Remember to parse the outputted JSON and then take the string out of it.
Second, `ref` is of type QString and the return value of `cmdj` is a JSON object..

Comment (nullsector) [reply src/widgets/StackWidget.cpp]: Currently I am on Debian (Buster) using QMake 3.1 / Qt 5.11.3 using the build instructions and am getting the same errors as described here #1797.  

Once I can get a build up, I will continue on this and check that everything works dynamically.

**Comment by ITAYC0HEN** [comment]
@nullsector we currently trying to solve this back-compatibility problem, meantime - can you try to update your environment and try with newer versions of the tool?

**Comment by nullsector** [comment]
@ITAYC0HEN I was able to get a build done. I will have time today to try and resolve the issue.

**Comment by ITAYC0HEN** [comment]
Seems like something happened in your last commit and introduced many changes that weren't changed by you. Right?

**Comment by nullsector** [comment]
@ITAYC0HEN Ahh yes, the fetch/merge pulled in the changes from b11ba24.

**Comment by ITAYC0HEN** [comment]
haha yeah it was suspecious. 
can you clean it please and force-push to your branch? 😅

**Comment by ITAYC0HEN** [comment]
ping @nullsector

**Comment by ITAYC0HEN** [comment]
@nullsector this is still looks wrong
